### PR TITLE
Add shell wrapper to dev build

### PR DESCRIPTION
**Pull request by noDGodyaev**
related to #40 

Need to add information about using it into README. (in this PR I will have merge conflicts cause of downstream of my branch)
instead of ``meson setup - install - export PYTHONPATH`` :

```shell
./dev.sh
```

### CODE REVIEW

**Comment by ev-br** [comment]
So to minimize conflicts, you prefer the readme update in this PR or elsewhere?

**Comment by noDGodyaev** [comment]
Maybe with documentaion changes?

**Comment by ev-br** [comment]
Then you can add a sentence "For convenience, we provide a `dev.sh` she'll script which encapsulates these steps", just before the
"Now the install is usable... " and hit the green button

**Comment by noDGodyaev** [comment]
It could be a possible solution.
But my branch is a little bit older and includes the old `readme`, that was before #38

**Comment by ev-br** [comment]
So if I just merge this as is, would it pose issues for you?

**Comment by noDGodyaev** [comment]
Nope

**Comment by ev-br** [comment]
Thanks, merged. Will update the readme later today

**Pull request merged**
